### ISSUE TITLE
Crash in LBAudioDetective Line 548

### ISSUE THREAD

**Issue by TheEngineerz** [lbrndnr/LBAudioDetective#1]
When i click on the Process Button at the top right then it Crashed on line

```
error = AudioUnitRender(inDetective->rioUnit, ioActionFlags, inTimeStamp, 1, inNumberFrames, &bufferList);
```

**Comment by johndpope** [comment]
You need to have the files setup correctly on iPhone.

I'm seeing the audio matching algorithm working by hard coding the files in LBViewController.m

```
-(id)init {
self = [super init];
if (self) {
    self.manager = [NSFileManager new];
    self.detective = LBAudioDetectiveNew();

    Float32 match = 0.0;
      NSLog(@"match:%f",match);

    NSURL* originalURL = [[NSBundle mainBundle] URLForResource:@"BlackBird" withExtension:@"caf"];
    NSURL* URL = [[NSBundle mainBundle] URLForResource:@"BlueTit" withExtension:@"caf"];

    LBAudioDetectiveCompareAudioURLs(self.detective, originalURL, URL, 0, &match);
    NSLog(@"match:%f",match);
  //  [matches setObject:@(match) forKey:originalBird];

}

return self;
```

}

**Comment by lbrndnr** [comment]
I'm so sorry, I totally forgot about this issue and haven't looked into this repo for a while. Thanks @jdp-global for helping me out. @TheEngineerz did you figure out how to use the object? Or is it still crashing?

**Comment by filipandrei87** [comment]
It's still crashing even with the above modifications

**Comment by lbrndnr** [comment]
Hi everybody,

Sorry for taking so long. Anyways, I made vast changes to the library and fixed the bug. The API changed a bit too with some functions I completely deleted. 

The test units work too now. So it should compile out of the box.

**Comment by johndpope** [comment]
Thx
